[build]
  command = "chmod +x ./build.sh && ./build.sh"
  publish = "frontend/dist"

[functions]
  directory = "backend/netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = "3.9"
  # Add your API keys here
  GROQ_API_KEY = "your_groq_api_key"

# CRITICAL: API redirects - this connects frontend to backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Frontend redirects for React Router
[[redirects]]
  from = "/*"  
  to = "/index.html"
  status = 200

# CORS headers for API requests
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
