# Multi-Chatbot Platform - Fixed Netlify Configuration
[build]
  # Fixed build command 
  command = "cd frontend && npm install && npm run build"
  
  # Publish the built frontend
  publish = "frontend/dist"
  
  # Functions directory at root level
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

# Your API redirects (these are working correctly)
[[redirects]]
  from = "/api/chatbots/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS headers (working correctly)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

[context.production.environment]
  NODE_ENV = "production"
